# Generated by Django 4.1.5 on 2023-06-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='images1',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='images1',
            new_name='images',
        ),
    ]
