# Generated by Django 4.1.5 on 2023-06-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_images1_doctor_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='images',
            new_name='image',
        ),
    ]
