# Generated by Django 4.1.5 on 2023-06-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_draftblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='username',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='draftblog',
            name='username',
            field=models.TextField(default='null'),
        ),
    ]
