# Generated by Django 4.1.5 on 2023-06-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_createblog_username_draftblog_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblog',
            name='username',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='draftblog',
            name='username',
            field=models.TextField(),
        ),
    ]
