# Generated by Django 4.1.5 on 2023-06-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_appoinment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='doctor',
            field=models.TextField(default='none'),
        ),
    ]
