# Generated by Django 4.1.5 on 2023-06-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_appoinment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='doctor',
            field=models.TextField(),
        ),
    ]
